version: '3.1' # if no version is specified, v1 is assumed. Recommend v2 minimum.

services:    # containers. same as docker run
  servicename:   # a friendly name. this is also DNS name inside network
    image:    # Optional if you use build
      jekyll/jekyll:3.8
    command:  # Optional, replace the default CMD specified by the image
      bash -c "sleep 30 && echo 'hello world'"
    environment: # Optional, same as -e in docker run
      - ENV1=VALUE1
      - ENV2=VALUE2
    volumes:     # Optional, same as -v in docker run
      - /host/path:/container/path

volumes:  # Optional, same as docker volume create
  vol1:

networks:  # Optional, same as docker network create
  net1:








