apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:  # match
    app: myapp
    type: front-end

# <myapp-service> with 3 replicas will be
# addressed @nodePort:30008 and can be
# reached curl http://192.168.1.2:300008
